<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackAsTool>true</PackAsTool>
    <AssemblyName>docman</AssemblyName>
    <ToolCommandName>docman</ToolCommandName>
    <PackageId>DocMan</PackageId>
    <Version>1.1.4</Version>
    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

</Project>
